In [1]:
# Import the necessary libraries
import pandas as pd

In [2]:
# Read the file containing the molecular structures
df_structures = pd.read_csv('./data/structures.csv')
df_structures.head()

      molecule_name  atom_index atom         x         y         z
0  dsgdb9nsd_000001           0    C -0.012698  1.085804  0.008001
1  dsgdb9nsd_000001           1    H  0.002150 -0.006031  0.001976
2  dsgdb9nsd_000001           2    H  1.011731  1.463751  0.000277
3  dsgdb9nsd_000001           3    H -0.540815  1.447527 -0.876644
4  dsgdb9nsd_000001           4    H -0.523814  1.437933  0.906397

In [3]:
# Read the file containing the training data
df_train = pd.read_csv('./data/train.csv')
df_train.head()

,id,molecule_name,atom_index_0,atom_index_1,type,scalar_coupling_constant
0,0,dsgdb9nsd_000001,1,0,1JHC,84.8076
1,1,dsgdb9nsd_000001,1,2,2JHH,-11.2570
2,2,dsgdb9nsd_000001,1,3,2JHH,-11.2548
3,3,dsgdb9nsd_000001,1,4,2JHH,-11.2543
4,4,dsgdb9nsd_000001,2,0,1JHC,84.8074

In [4]:
# Define a method to merge the molecular strutures
# into the training/testing data
def merge_molecule_structure(data: pd.DataFrame):
    atom_idx = [0, 1]
    
    for idx in atom_idx:
        
        data = data.merge( df_structures, how='left',
                       left_on=['molecule_name', f'atom_index_{idx}'],
                       right_on=['molecule_name', 'atom_index'])
        
        data = data.drop('atom_index', axis=1)
        data = data.rename(columns={'atom': f'atom_{idx}',
                                    'x': f'x_{idx}',
                                    'y': f'y_{idx}',
                                    'z': f'z_{idx}'})
        
    return data

In [5]:
df_train = merge_molecule_structure(df_train)
df_train.head()

,id,molecule_name,atom_index_0,atom_index_1,type,scalar_coupling_constant,atom_0,x_0,y_0,z_0,atom_1,x_1,y_1,z_1
0,0,dsgdb9nsd_000001,1,0,1JHC,84.8076,H,0.002150,-0.006031,0.001976,C,-0.012698,1.085804,0.008001
1,1,dsgdb9nsd_000001,1,2,2JHH,-11.2570,H,0.002150,-0.006031,0.001976,H,1.011731,1.463751,0.000277
2,2,dsgdb9nsd_000001,1,3,2JHH,-11.2548,H,0.002150,-0.006031,0.001976,H,-0.540815,1.447527,-0.876644
3,3,dsgdb9nsd_000001,1,4,2JHH,-11.2543,H,0.002150,-0.006031,0.001976,H,-0.523814,1.437933,0.906397
4,4,dsgdb9nsd_000001,2,0,1JHC,84.8074,H,1.011731,1.463751,0.000277,C,-0.012698,1.085804,0.008001